/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuração pública da loja (RF-008) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            loja: {
                                /** @example FitMoveOn */
                                nome: string;
                                /** @example Unidade Centro */
                                unidade: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vendedores ativos (RF-001)
         * @description Com um único vendedor, o front pula a etapa "Quem está vendendo?".
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            vendedores: components["schemas"]["Vendedor"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login por PIN (RF-002) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example carlos */
                        vendedorId: string;
                        /** @example 12345678 */
                        pin: string;
                    };
                };
            };
            responses: {
                /** @description Sessão criada; cookie `pdv_sessao` (com Expires na meia-noite local) enviado em Set-Cookie. */
                200: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RespostaVendedor"];
                    };
                };
                400: components["responses"]["ErroEntrada"];
                /** @description `senha_incorreta` — PIN errado, ou vendedor inexistente/inativo (mesma resposta). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vendedor da sessão atual (RF-003) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RespostaVendedor"];
                    };
                };
                401: components["responses"]["SemSessao"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerra a sessão (RF-003)
         * @description Idempotente; funciona mesmo sem cookie ou com cookie já inválido.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sessão encerrada e cookie removido. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catálogo ativo na ordem de exibição (RF-004) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Catalogo"];
                    };
                };
                401: components["responses"]["SemSessao"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra uma venda (RF-005) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VendaEntrada"];
                };
            };
            responses: {
                /** @description Chave de idempotência já usada por este vendedor — devolve a venda original. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RespostaVenda"];
                    };
                };
                /** @description Venda criada. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RespostaVenda"];
                    };
                };
                /**
                 * @description `entrada_invalida` (formato), `sem_itens`, `sem_pagamento`, `item_invalido`
                 *     (SKU inexistente ou inativo), `item_repetido` (mesmo SKU em duas linhas), `telefone_invalido` (celular sem 11 dígitos).
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                401: components["responses"]["SemSessao"];
                /**
                 * @description `chave_em_uso` — a chave de idempotência pertence a venda de outro vendedor.
                 *     `sem_estoque` — alguma peça pedida acima do saldo; a mensagem nomeia as peças e nada é gravado.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendas/hoje": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vendas de hoje do vendedor logado (RF-006) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VendasDoDia"];
                    };
                };
                401: components["responses"]["SemSessao"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendas/{numero}/cupom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cupom não fiscal de uma venda (RF-007) */
        get: {
            parameters: {
                query?: {
                    colunas?: "48" | "32";
                };
                header?: never;
                path: {
                    numero: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cupom"];
                    };
                };
                400: components["responses"]["ErroEntrada"];
                401: components["responses"]["SemSessao"];
                /** @description `venda_nao_encontrada` */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "erro": {
         *         "codigo": "senha_incorreta",
         *         "mensagem": "Senha incorreta. Tente de novo."
         *       }
         *     }
         */
        Erro: {
            erro: {
                /** @enum {string} */
                codigo: "entrada_invalida" | "senha_incorreta" | "sessao_invalida" | "sem_itens" | "sem_pagamento" | "item_invalido" | "item_repetido" | "telefone_invalido" | "chave_em_uso" | "sem_estoque" | "venda_nao_encontrada" | "rota_nao_encontrada" | "erro_interno";
                mensagem: string;
            };
        };
        Vendedor: {
            /** @example carlos */
            id: string;
            /** @example Carlos */
            nome: string;
            /** @example Vendedor · loja */
            cargo: string;
        };
        RespostaVendedor: {
            vendedor: components["schemas"]["Vendedor"];
            /**
             * Format: date-time
             * @description Próxima meia-noite no fuso da loja, em ISO-8601 UTC. Depois disso a API responde 401.
             * @example 2026-09-26T03:00:00.000Z
             */
            expiraEm: string;
        };
        /**
         * @description Catálogo do ERP (integração PDV-ERP): produtos ativos com ao menos um SKU ativo, cada um com
         *     seus SKUs ativos (cor → tamanho) e o saldo em estoque. Tipos e produtos em ordem alfabética;
         *     SKUs pela ordem da cor (número) e do tamanho (grade).
         */
        Catalogo: {
            /** @description Só os tipos que têm produto na lista. */
            tipos: {
                /** @example 1 */
                id: number;
                /** @example Calças */
                nome: string;
            }[];
            produtos: {
                /** @example 1 */
                id: number;
                /** @example 1 */
                numero: number;
                /** @example Calça Legging */
                nome: string;
                /** @example 1 */
                tipoId: number;
                /** @example Suplex */
                tecidoNome: string;
                skus: components["schemas"]["SkuCatalogo"][];
            }[];
            pagamentos: {
                /** @example pix */
                id: string;
                /** @example Pix */
                nome: string;
            }[];
        };
        SkuCatalogo: {
            /** @example 2 */
            id: number;
            /** @example 0001.001.02 */
            codigo: string;
            /** @description Cor lisa tem hex; estampa pode ter só a foto. */
            cor: {
                /** @example 1 */
                id: number;
                /** @example Preto */
                nome: string;
                /** @example #1B1B1B */
                hex: string | null;
                fotoUrl: string | null;
            };
            tamanho: {
                /** @example M */
                sigla: string;
                /** @example 2 */
                ordem: number;
            };
            /** @example 8900 */
            precoCentavos: number;
            /** @example 5 */
            saldo: number;
        };
        ItemVendaEntrada: {
            /**
             * @description Id do SKU no catálogo
             * @example 2
             */
            skuId: number;
            /** @example 2 */
            qtd: number;
            /**
             * @example 10
             * @enum {integer}
             */
            descPercent: 0 | 5 | 10 | 15;
        };
        /**
         * @description O front NÃO envia preços: o servidor usa o preço do SKU. Campos não previstos
         *     (ex.: `precoUnitCentavos`) são recusados com 400 `entrada_invalida`.
         *     `chaveIdempotencia` é um UUID gerado pelo aparelho por venda; reenviar a mesma chave
         *     devolve a venda já gravada (200) em vez de criar outra.
         */
        VendaEntrada: {
            /** Format: uuid */
            chaveIdempotencia: string;
            itens: components["schemas"]["ItemVendaEntrada"][];
            /**
             * @default 0
             * @example 1500
             */
            descontoTotalCentavos: number;
            /**
             * @default
             * @example Maria
             */
            cliente: string;
            /**
             * @description Opcional. Celular do cliente com DDD: dígitos, espaços, parênteses e hífen; depois de tirar a máscara precisa ter exatamente 11 dígitos (senão 400 telefone_invalido). Gravado só com os dígitos. O campo cpf deixou de existir (corpo com cpf → 400 entrada_invalida).
             * @default
             * @example (31) 98765-4321
             */
            telefone: string;
            /** @example pix */
            pagamentoId?: string;
        };
        ItemVenda: {
            /** @description Vendas pelo catálogo do ERP: "produto:<número>"; vendas antigas: id do modelo do PDV. */
            modeloId: string;
            /** @example Calça Legging */
            modeloNome: string;
            /** @description Vendas pelo catálogo do ERP: "tecido:<id>"; vendas antigas: id do tecido do PDV. */
            tecidoId: string;
            /** @example Suplex Light */
            tecidoNome: string;
            /** @example M */
            tamanho: string;
            /** @example Preto */
            cor: string;
            /** @example 2 */
            qtd: number;
            /** @example 10100 */
            precoUnitCentavos: number;
            /** @example 10 */
            descPercent: number;
            /** @example 18180 */
            subtotalCentavos: number;
        };
        Venda: {
            /** @example 1042 */
            numero: number;
            /** Format: date-time */
            dataHora: string;
            /** @example 14:35 */
            hora: string;
            vendedor: {
                id: string;
                nome: string;
            };
            cliente: string;
            /**
             * @description Celular só com dígitos (11)
             * @example 31987654321
             */
            telefone: string;
            pagamento: {
                id: string;
                nome: string;
            };
            itens: components["schemas"]["ItemVenda"][];
            /** @example 3 */
            pecas: number;
            /** @example 25700 */
            brutoCentavos: number;
            /** @example 2020 */
            descontoItensCentavos: number;
            /** @example 1500 */
            descontoTotalCentavos: number;
            /**
             * @description itens + total
             * @example 3520
             */
            descontosCentavos: number;
            /**
             * @description max(0, bruto − descontos)
             * @example 22180
             */
            totalCentavos: number;
        };
        RespostaVenda: {
            venda: components["schemas"]["Venda"];
        };
        VendasDoDia: {
            /** @description Da mais recente para a mais antiga; só do vendedor logado, só de hoje. */
            vendas: {
                /** @example 1042 */
                numero: number;
                /** @example Maria */
                cliente: string;
                /** @example 14:35 */
                hora: string;
                /** @example 3 */
                pecas: number;
                /** @example Pix */
                pagamento: string;
                /** @example 22180 */
                totalCentavos: number;
            }[];
            /** @example 22180 */
            totalDiaCentavos: number;
            /** @example 1 */
            quantidadePedidos: number;
        };
        Cupom: {
            /** @enum {integer} */
            colunas: 48 | 32;
            /** @description Linhas de largura fixa separadas por "\n", em UTF-8. O aparelho converte para o codepage da impressora. */
            texto: string;
            dados: {
                loja: {
                    nome: string;
                    unidade: string;
                    endereco: string;
                    telefone: string;
                };
                /** @example NÃO É DOCUMENTO FISCAL */
                aviso: string;
                numero: number;
                /** @example 25/09/2026 */
                data: string;
                /** @example 14:35 */
                hora: string;
                vendedor: string;
                cliente: string;
                /**
                 * @description Celular do cliente formatado, ou vazio. Não é o telefone da loja (loja.telefone).
                 * @example (31) 98765-4321
                 */
                telefoneCliente: string;
                itens: {
                    modelo: string;
                    /** @example Suplex Light · Tam M · Preto */
                    variacao: string;
                    qtd: number;
                    precoUnitCentavos: number;
                    descPercent: number;
                    subtotalCentavos: number;
                }[];
                pecas: number;
                brutoCentavos: number;
                descontosCentavos: number;
                totalCentavos: number;
                pagamento: string;
            };
        };
    };
    responses: {
        /** @description Entrada inválida */
        ErroEntrada: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erro"];
            };
        };
        /** @description Sem sessão válida (`sessao_invalida`) */
        SemSessao: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erro"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
